name: Build and Deploy the image to Dockerhub
on: [push]

jobs:
  build:
    name: Build and Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: tuxuser/lg-webos-ndk:latest
          cache-from: type=registry,ref=tuxuser/lg-webos-ndk:latest
          cache-to: type=inline
